### PR TITLE
Remove Python 2 compatibility code

### LINKED ISSUE #5: Consider removing Python 2 compatibility code
Hello,

README says:

> fbtftp is written in python3 [...]

and lists Python 3.x as a requirement at https://github.com/facebook/fbtftp#requirements. setup.py also defines it as a Python 3 only project: https://github.com/facebook/fbtftp/blob/master/setup.py#L41

However, the code base has some code for Python 2 compatibility (`__future__` imports, `codecs.open`, `class Spam(object):` etc.) and follows some old practices like https://github.com/facebook/fbtftp/blob/master/examples/server.py#L68.

Is there any Python 2 deployment out there (probably not since it will require the backport of ipaddress module) or can they be safely removed now? I can send a pull request if they are not needed now.

Thanks!

### PR DESCRIPTION
**Pull request by berkerpeksag**
Closes #5

This pull request also includes three cleanups in separate commits.

### CODE REVIEW

**Comment by pallotron** [comment]
good stuff, I have been working on some of this already, you should see a commit landing to master shortly, please rebase your repo and resolve any merge conflict, if any.

**Comment by pallotron** [comment]
made some changes in a4780e86eab1b424191aa4262013dfa81c8af7cb, feel free to rebase/resolve conflicts now :)

**Comment by pallotron** [comment]
can you also change the Example section in the `README.md` file? :)

**Comment by berkerpeksag** [comment]
Will do in a moment, thanks!

By the way, using `super(self.__class__, self)` over `super(ClassName, self)` (or simply `super()`) can cause subtle bugs in subclasses since the former will try to invoke subclass' method instead of parent's method. Here is a good example to demonstrate the problem: https://gist.github.com/ulope/1935894

Do you want me keep them as in https://github.com/facebook/fbtftp/commit/a4780e86eab1b424191aa4262013dfa81c8af7cb or change them to `super(ClassName, self)` or `super()`?

**Comment by pallotron** [comment]
you can change them as long as `make test` passes.

**Comment by pallotron** [comment]
any update?

**Comment by pallotron** [comment]
@facebook-github-bot shipit

**Comment by berkerpeksag** [comment]
Thanks for merging this so quickly. I'm glad Facebook is using Python 3 on production :)

**Pull request closed without merging**
