### PR TITLE
Properly attribute authorship

### PR DESCRIPTION
**Pull request by marcinwyszynski**
This is a blast from a past that feels so very, very distant now. But still, the ethics of signing what's essentially 60% someone else's work and 100% someone else's idea is... let's say... dubious? There will be a ton of other things to rightfully and exclusively slap your name on, Angelo. But this is not one of them.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @pallotron, @insomniacslk and @berkerpeksag to be potential reviewers.

**Comment by pallotron** [comment]
No problem, I will change that now.

**Comment by pallotron** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/248890555477702/int_phab) to review.

**Pull request closed without merging**
