### PR TITLE
Switched travis-ci from .com to .org

### PR DESCRIPTION
**Pull request by insomniacslk**
I've replaced the link from travis-ci.com to .org to reflect the current status

### CODE REVIEW

**Comment by insomniacslk** [comment]
This is failing because of a regression in the tests introduced a commit ago - subtests are only supported from python 3.4 on[1], and the test matrix is covering python 3.3 too. I would not remove py3.3 from the test matrix though, since it seems to still be the most popular 3.x out there.

[1] https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests

**Comment by pallotron** [comment]
@facebook-github-bot shipit

**Comment by berkerpeksag** [comment]
Oh sorry, I totally forgot 3.3. I'm not so sure 3.3 is the most popular Python 3 release anymore. Last time (~1 year ago) I saw download statistics 3.4 was the most popular one. 3.3 is also not developing by Python core devs anymore (it will get security fixes until September 2017).

**Comment by insomniacslk** [comment]
@berkerpeksag sounds good, we'll drop 3.3 in the next commit :)

**Pull request closed without merging**
